### ISSUE TITLE
[BUG] Beam Weapon VFX Not Drawn from Remote Client

### ISSUE THREAD

**Issue by wail** [OpenTournament/OpenTournament#267]
**Bug Description**
Beam weapon effects not drawn for remote clients

**To Reproduce**
1. Use PIE
2. Set Clients > 1 & Local Multiplayer Server
3. Position Host1 and Client2
4. Using Client2, fire a beam weapon
5. Observe Host1 does not see beam effects

**Expected Behavior**
Beam effects are drawn for all clients.

**Comment by ChatouilleGG** [comment]
Listen server support was intentionally left out of all networking code I've been working on.

Supporting listen server mode, in addition to standalone and dedicated server, is a substantial headache of additional edge cases to handle, for a rather niche usage, which is easily solved the way UT4 did : launch a local dedicated server process in the background and connect to it.

To add to that, many client-side features like prediction, smoothing, interpolation, or extrapolation, cannot be properly implemented in listen server mode due to its nature - as an authority server it is meant to represent truth and those features would divert it from that role. As a result it would either suck at being an authority, or suck at being a client (ie. game looking smooth and fluid).
