### ISSUE TITLE
[Design][Discussion] Fall Damage Mechanic

### ISSUE THREAD

**Issue by wail** [OpenTournament/OpenTournament#80]
Trying something different with issues, not sure if this will be sucessful but worth a shot.

**Context**
Traditionally, players will take damage from falls if their speed when landing exceeds a certain threshold, scaling up based on the magnitude by which the threshold is exceeded. In certain cases, players may be able to pick up an item in maps that will reduce or eliminate the possibility of fall damage. Typically the possibility of death by fall damage can also be mitigated via healing items, armors, and certain movement techniques.

**Question**
Does damage from long falls contribute to the game's design in any way, or unnecessarily limit map design?

**Comment by septemalteri** [comment]
This is an element that could possibly be utilized to reward team coordination such as team boosting. 

It could also serve in solo situations such as in CTF where a player might get shot from behind let's say, forcing him to take falling damage, but should they land on a healthpack before, it would allow them to survive. 

These "luck > skill" moments that I personally think should be seen as an opportunity instead of something limiting when it comes to design. 

I understand that it doesn't directly answer the question but yoshi needs to chill.

**Comment by DarkArc** [comment]
Might be interesting to see some sort of "roll" mechanic, where a player with good timing can negate significant fall damage.

**Comment by Niklot-OT** [comment]
1. I find it absolutely ridiculous that in QuakeWorld or UT one can die by falling off a ledge with low hp.
2. Disabling fall damage might feel good on one end, but then it eliminates the risk/reward kind of factor when jumping off certain heights.
3. Disabling fall damage disables all kind of punishment for players who want to jump from places like the sniper tower on DM-Phobos.
4. Fall damage makes environment traversal a bit more tactical and forces more careful maneuvering.
5. Fall damage gained redundancy with double jumping and more extreme movement introduced in later UT titles, since there was significantly more air time in them than in og UT.
6. Ridiculous 2hp fall damage deaths could be prevented by a crippled state, so falling off higher ledges would rather be more slowing over a short period of time than damaging and wouldn't be lethal unless in extreme situations (DM-Phobos sniper tower).

**Comment by Joelllll** [comment]
> 2. Disabling fall damage might feel good on one end, but then it eliminates the risk/reward kind of factor when jumping off certain heights.

If this is desirable how to add risk to falling without damage? Audio for falling players followed by a crunchier footstep sound when landing? This would be good regardless of damage. Player drops currently equipped weapon forwards some amount based on fall height, etc. 

The "risk" of jumping off something that causes 30hp damage is not really something (imo) that players will be constantly weighing up and only care about it when they are low on health - otherwise they will just eat the damage and then heal up. This is particularly true in ut games with higher player counts where armor is relatively rare (3-5 times per minute) but health packs are much more common due to 20s spawn. 

> 3. Disabling fall damage disables all kind of punishment for players who want to jump from places like the sniper tower on DM-Phobos.

At the same time it opens up being able to jump from this location which can be super cool as well. Possibly cooler/more interesting than "pay the 50hp to jump down" tax. Obv phobo tower is death..

Also air time in afps is typically a state where players are more vulerable. Falling allows easier tracking (as do features like bounce pads and lift jumps) so falling could be said to be a disadvantage due to this. Thinking back to point 2 and risk/reward - highground is beneficial, it takes a special something-something to make a player cede highground. Perhaps it is ok not having fall damage to make giving up high ground more appealing in more situations? Not directly punishing the fall as it is already punished by (probable) loss of good posistion.

> 4. Fall damage makes environment traversal a bit more tactical and forces more careful maneuvering.
This is not that common really. On most maps this equates to taking small amount of chip damage while moving around and jumping off "normal" sized geometry. Large scale breaks the games scale to a degree with the travel time vs 

6. Ridiculous 2hp fall damage deaths could be prevented by a crippled state, so falling off higher ledges would rather be more slowing over a short period of time than damaging and wouldn't be lethal unless in extreme situations (DM-Phobos sniper tower).

A cripple effect on landing could be interesting - but also annoying af if it triggers frequently. Perhaps no fall damage for what you would traditionally take damage from and then.. instant death above a certain (reasonable) height?

If a cripple state were used frequently for lower falls that one might find on normal maps it would potentially be significantly worse than taking the (generally) low damage as a crippled player becomes an easy target. 
Another thing to keep in mind is slide, which has been requested often. Being able to fall to gain velocity which can then be converted into slide is nice.

**Comment by wail** [comment]
I'd been holding off on chiming in on this since I didn't want to necessarily influence others, but it's been awhile so here goes.

**Cons**

* Dying from falling damage is often a feelsbad moment
* Dying from falling damage doesn't enhance the feel of hyper-badass athletes with advanced sci-fi equipment
* Falling damage might be seen as enforcing arbitrary limitations on map design

**Pros**

* Intuitive. When you fall a long distance and take damage no one thinks this is unusual
* Scalable effect. There's a difference between falling and taking 5 damage and taking 100 damage.
* Some map designs are essentially impossible without falling damage (e.g. CTF-Face completely changes)
* Pickups such as Jump Boots (or, newly-proposed 'Featherfall Boots') can mitigate falling damage.
* There are multiple strategies available to allow level designers to design maps with extensive use of verticality without having players constantly be under threat of falling damage. (e.g. Water volumes, lots of Featherfall Boot pickups, or using a level blueprint to automatically assign all players a Featherfall Boot item on spawn.)


Two other important considerations:

* Falling damage is already implemented
* Falling damage is an expected convention

Alternate proposals like 'stagger' are really beyond the scope of the discussion here because that's proposing a new feature and one that has a lot of questions & vagueness that would need to be clearly answered before we could judge its impact on the game.

**Comment by wail** [comment]
Closing issue here, pending discussion in OT-#206
