### ISSUE TITLE
[Code][Feature] Weapon drop / throw

### ISSUE THREAD

**Issue by ChatouilleGG** [OpenTournament/OpenTournament#82]
Implement weapon drop
- on death
- on command / keybind

Required :
- Limited life time.
- Dropped weapon should have a slight delay before it can be picked up again by the same person.
- Drop/throw logic must be reusable as we'll need it for powerups later on.

Optional :
- Fade out effect.
- Throw arc/velocity depends on player's velocity, allowing player to toss a weapon further away or upwards for a teammate.

Questions :
- How to deal with ammo? In case of death, it is obvious the dropped weapon should contain all available ammo. In case of throw it is not obvious, especially if we have ammo types shared by multiple weapons. For example if RL and GL use same ammo, I don't want to run out of GL ammo just because I threw my RL. Should it go 50/50 is that case?

**Comment by wail** [comment]
>    Throw arc/velocity depends on player's velocity, allowing player to toss a weapon further away or upwards for a teammate.

Rate this as highly optional since if we do that I think inheritance should not be more than arbitrary-figure ~10% of velocity. Throwing something and having it inherit velocity while strafing for example is usually pretty disorienting given how players are trained to expect shooting things works.

>     * How to deal with ammo? In case of death, it is obvious the dropped weapon should contain all available ammo. In case of throw it is not obvious, especially if we have ammo types shared by multiple weapons. For example if RL and GL use same ammo, I don't want to run out of GL ammo just because I threw my RL. Should it go 50/50 is that case?

TBH in this type of case I would expect either:
* The thrown gun doesn't get any of the shared ammo type. Intuitively no player throwing a weapon would expect there to be a side effect like reducing ammo for some other weapon. If another player picks up the weapon they'll need to find ammo.
* Make a player-configurable value. 0...1.0 which determines what percentage of shared ammo is given to a shared weapon.

**Comment by TamzidFarhan** [comment]
> How to deal with ammo? In case of death, it is obvious the dropped weapon should contain all available ammo. In case of throw it is not obvious, especially if we have ammo types shared by multiple weapons. For example if RL and GL use same ammo, I don't want to run out of GL ammo just because I threw my RL. Should it go 50/50 is that case?

I'd suggest a drop system similar to Apex Legends: 

- Dropped weapons revert back to the base ammo count
- Any extra ammo for that weapon in the players inventory gets dropped as well as ammo pickup

**Comment by wail** [comment]
Possibility to have a throw ammo option as well, although I would consider this overkill. Particularly since some weapons might have more than one ammo type, and therefore we'd need a design & probably UI to determine how a player could select what ammo type to drop.

Alternatively, implement trade menu & auction house for players to trade weapons & ammo.

**Comment by ChatouilleGG** [comment]
done in 08c51bbbe76569d052c3f276c9d667e92c161fd2
